puts "The students of my cohort at Makers Academy"
puts "-----------------"

puts "Mario Gintili"
puts "Rick Brunstedt"
puts "Mikhail Dubov"
puts "Karolis Noreika"
puts "Michael Sidon"
puts "Charles de Barros"
puts "Ruslan Vikhor"
puts "Toby Retallick"
puts "Mark Mekhail"
puts "Sarah Young"
puts "Hanna Wight"
puts "Khushkaren Singh"
puts "Manjit Singh"
puts "Alex Gaudiosi"
puts "Ross Hepburn"
puts "Natascia Marchese"
puts "Tiffanie Chia"
puts "Matthew Thomas"
puts "Freddy McGroarty"
puts "Tyler Rollins"
puts "Richard Curteis"
puts "Anna Yanova"
puts "Andrew Cumine"

print "Overall, we have "
print 23
print " great students"